### PR TITLE
Debounce compilation on watch (100ms).

### PR DESCRIPTION
**Pull request by millette**
Currently, if you're watching 5 tags and save 2 simultaneously in your editor, the 5 tags are compiled twice (once for each file that changed). With a short debounce, we get a single compilation pass.

### CODE REVIEW

**Comment by millette** [comment]
For some reason lodash.debounce isn't getting installed (not found in node_modules/) so I tried again with the full lodash.

Running the tests locally, I get this error:

```
stdin -> test/generated/stdinout/output.js
make: ./node_modules/.bin/istanbul: commande introuvable
Makefile:40: recipe for target 'test-mocha' failed
make: *** [test-mocha] Error 127
error Command failed with exit code 2.
```

**Comment by millette** [comment]
Finally!

I'd appreciate it if someone can tell me why require('lodash).debounce works, but require('lodash.debounce) doesn't.

**Comment by GianlucaGuarini** [comment]
hi @millette thanks for your pull request but I would like to avoid lodash dependencies, please use this [simple debounce implementation](https://github.com/riot/route/blob/master/src/index.js#L64-L76)

**Comment by millette** [comment]
Should I simply copy that implementation into tasks/watch.js ?

**Comment by millette** [comment]
Note also that lodash is already a depency down the chain.

```
$ yarn why lodash
...
[4/4] Calculating file sizes...
info Reasons this module exists
   - "riot-compiler#string-similarity" depends on it
   - "eslint" depends on it
   - "eslint#inquirer" depends on it
```

**Comment by millette** [comment]
I don't know how picky you are about PRs. Should I include https://github.com/millette/cli/pull/1/commits/c8c2c28dc0c0faeee595bc4fece9dc7b41f1ff88 in the current PR or provide a second one?

**Comment by GianlucaGuarini** [comment]
@millette please add the simple debounce method somewhere [here](https://github.com/riot/cli/blob/master/lib/helpers.js) and i will be happy to merge your PR

**Comment by millette** [comment]
Regarding <https://github.com/riot/cli/pull/29#issuecomment-353806160> do you want a 2nd PR to replace babel with babel-cli and coffee-script with coffeescript?

**Comment by GianlucaGuarini** [comment]
thank you I need to work on the repo anyway so your PR is enough for now

**Pull request merged**
